### PR TITLE
Routes tab

### PR DESCRIPTION
**Pull request by connorroth20**
Created a routes tab that fetches data from the API and places it within a dropdown and a flatlist view.
The user is able to filter by stop to see the current list of busses that go to that stop

TODO:
* Add navigation, when you click on a route, it will take you to another screen that has more route details
* Fix dropdown to change the text to the selected route
* Styling

### CODE REVIEW

**Comment by tikkikkit21** [comment]
[Routes tab](https://trello.com/c/NoRyTPcH/24-routes-tab)

**Review by tikkikkit21 — APPROVED** [review]
One thing I noticed is that when you filter by stop, there's no way to go back to displaying all routes again. We can fix it next sprint, I'll add a card to the Trello.

Overall very pretty routes tab! 😍

**Comment by connorroth20** [comment]
> One thing I noticed is that when you filter by stop, there's no way to go back to displaying all routes again. We can fix it next sprint, I'll add a card to the Trello.
> 
> Overall very pretty routes tab! 😍

this is a good point, ill add something tot he top of the picker and says "all routes" or something like that

**Review by tikkikkit21 — APPROVED** [review]

**Comment by tikkikkit21** [comment]
I'm going to try and fix the git dupes

**Comment by tikkikkit21** [comment]
Replaced with #11 for cleaner Git history

**Pull request closed without merging**
